### ISSUE TITLE
Scripts not running

### ISSUE THREAD

**Issue by codechair** [SNathJr/ghost-on-heroku#30]
Hi, just tried to deploy. Any idea of how to get around the below (happens when scripts are run in Heroku)?

**Got this:**

```
Initializing the deployment…
pwd →
/app
config.production.json →
cat: config.production.json: No such file or directory
Awaiting MySQL database…
Database connected.
[2020-01-09 16:18:50] [31mERROR[39m connect ECONNREFUSED 127.0.0.1:3306
[31m
[31mconnect ECONNREFUSED 127.0.0.1:3306[39m

[33m"Unknown database error"[39m

[1m[37mError ID:[39m[22m
    [90m500[39m

[1m[37mError Code: [39m[22m
    [90mDATABASE_CREATION_FAILED[39m

[90m----------------------------------------[39m

[90mDatabaseError: connect ECONNREFUSED 127.0.0.1:3306
    at DatabaseError.KnexMigrateError (/app/node_modules/knex-migrator/lib/errors.js:7:26)
    at new DatabaseError (/app/node_modules/knex-migrator/lib/errors.js:55:26)
    at /app/node_modules/knex-migrator/lib/database.js:126:19
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

DatabaseError: connect ECONNREFUSED 127.0.0.1:3306
    at DatabaseError.KnexMigrateError (/app/node_modules/knex-migrator/lib/errors.js:7:26)
    at new DatabaseError (/app/node_modules/knex-migrator/lib/errors.js:55:26)
    at connection.raw.catch (/app/node_modules/knex-migrator/lib/database.js:47:19)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
    --------------------
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/app/node_modules/mysql/lib/Connection.js:119:18)
    at _bluebird.default (/app/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:82:18)
    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/app/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:77:12)
    at create (/app/node_modules/knex-migrator/node_modules/knex/lib/client.js:282:21)
    at utils_1.tryPromise (/app/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/app/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/app/node_modules/tarn/lib/Pool.js:315:17)
    at Promise._execute (/app/node_modules/ghost/node_modules/bluebird/js/release/debuggability.js:427:9)
    at Promise._resolveFromExecutor (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:103:10)
    at callbackOrPromise (/app/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/app/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/app/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/app/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/app/node_modules/tarn/lib/Pool.js:85:14)
    at _bluebird.default.try (/app/node_modules/knex-migrator/node_modules/knex/lib/client.js:333:50)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)[39m
[39m
```

**Comment by SNathJr** [comment]
Hey @codechair 

Could you give more info on what you were trying to do when this happened?

Regards,
SNathJr

**Comment by JaneJeon** [comment]
The error message is clear - it can't connect to MySQL. Double-check your MySQL configuration: check what key the database url is set under in environment variable settings, and check that the URL _actually_ points to the MySQL instance you have running.

Try connecting to it from your local MySQL shell using the URL provided, and _if it works_, then please report back to us with your config. Thanks.

Otherwise, it's a simple misconfiguration on your end.

**Comment by SNathJr** [comment]
> @codechair The error message is clear - it can't connect to MySQL. Double-check your MySQL configuration: check what key the database url is set under in environment variable settings, and check that the URL _actually_ points to the MySQL instance you have running.
> 
> Try connecting to it from your local MySQL shell using the URL provided, and _if it works_, then please report back to us with your config. Thanks.
> 
> Otherwise, it's a simple misconfiguration on your end.

That would be the case if @codechair is trying to push to heroku from local, if doing so one needs to make sure that heroku has all those config vars beforehand.

**Comment by codechair** [comment]
Thanks @SNathJr @JaneJeon for the support.

What I've done was to follow the instructions in the video: https://www.youtube.com/watch?v=cODvhXMHgYI


And despite things being a bit different as of now (no cloudinary variables input are requested - see image), I've tried giving the build cloudinary API keys etc instead of S3 bucket keys etc. It did not work. The logs above are from the step ("Run scripts & scale dynos
Postdeploy exit code was not 0") coming right after "Build App" in the heroku dashboard.

<img width="703" alt="Screenshot 2020-01-09 at 19 27 45" src="https://user-images.githubusercontent.com/41295753/72098600-b5c36500-3316-11ea-89ce-3e26da8286d3.png">

So, I'm unsure what is off and any pointers are welcome.

**Comment by SNathJr** [comment]
Hey @codechair 

There is no need to manually input cloudinary key and username etc now. You just give your app a name and an APP_PUBLIC_URL and ghost will work out of the box.

Cheers!

**Comment by codechair** [comment]
Thanks again @SNathJr !

I confirm this now worked.

Which storage I am using then? I'm using clodinary then, but under which account? Who is owning the images? 

Where do I place my Cloudinary Access keys?

**Comment by codechair** [comment]
AWESOME work @SNathJr . 

I've now been able to understand the whole setup better when digging into the configuration setup in heroku.

Thanks for the great work!

**Comment by SNathJr** [comment]
Hey @codechair 

Awesome, happy to be of help :)
