### ISSUE TITLE
Testing Locally with heroku local

### ISSUE THREAD

**Issue by kalverra** [SNathJr/ghost-on-heroku#63]
I'm looking to test the code locally with `heroku local` so I can test changes made before pushing to a branch. I keep running into issues though, most recently below.

```
$ heroku local
7:38:39 PM web.1 |  > ghost-on-heroku@3.2.0 start D:\Projects\demon-lace
7:38:39 PM web.1 |  > node server.js
7:38:39 PM web.1 |  D:\Projects\demon-lace\node_modules\ghost\core\shared\config\utils.js:103
7:38:39 PM web.1 |          delete database.connection.host;
7:38:39 PM web.1 |                          ^
7:38:39 PM web.1 |  TypeError: Cannot read property 'connection' of undefined
7:38:39 PM web.1 |      at exports.Provider.sanitizeDatabaseProperties (D:\Projects\demon-lace\node_modules\ghost\core\shared\config\utils.js:103:25)
7:38:39 PM web.1 |      at Object.loadNconf (D:\Projects\demon-lace\node_modules\ghost\core\shared\config\index.js:52:11)
7:38:39 PM web.1 |      at Object.<anonymous> (D:\Projects\demon-lace\node_modules\ghost\core\shared\config\index.js:83:27)
7:38:39 PM web.1 |      at Module._compile (internal/modules/cjs/loader.js:1063:30)
7:38:39 PM web.1 |      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
7:38:39 PM web.1 |      at Module.load (internal/modules/cjs/loader.js:928:32)
7:38:39 PM web.1 |      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
7:38:39 PM web.1 |      at Module.require (internal/modules/cjs/loader.js:952:19)
7:38:39 PM web.1 |      at require (internal/modules/cjs/helpers.js:88:18)
7:38:39 PM web.1 |      at Object.<anonymous> (D:\Projects\demon-lace\node_modules\ghost\core\server\index.js:14:16)
7:38:39 PM web.1 |      at Module._compile (internal/modules/cjs/loader.js:1063:30)
7:38:39 PM web.1 |      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
7:38:39 PM web.1 |      at Module.load (internal/modules/cjs/loader.js:928:32)
7:38:39 PM web.1 |      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
7:38:39 PM web.1 |      at Module.require (internal/modules/cjs/loader.js:952:19)
7:38:39 PM web.1 |      at require (internal/modules/cjs/helpers.js:88:18)
7:38:39 PM web.1 |  npm
7:38:39 PM web.1 |   ERR! code ELIFECYCLE
7:38:39 PM web.1 |  npm ERR! errno 1
7:38:39 PM web.1 |  npm
7:38:39 PM web.1 |  ERR! ghost-on-heroku@3.2.0 start: `node server.js`
7:38:39 PM web.1 |  npm ERR! Exit status 1
7:38:39 PM web.1 |  npm ERR!
7:38:39 PM web.1 |  npm ERR! Failed at the ghost-on-heroku@3.2.0 start script.
7:38:39 PM web.1 |  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
7:38:39 PM web.1 |  npm ERR! A complete log of this run can be found in:
7:38:39 PM web.1 |  npm ERR!
7:38:39 PM web.1 |       C:\Users\Adam\AppData\Roaming\npm-cache\_logs\2020-12-02T00_38_39_550Z-debug.log
[DONE] Killing all processes with signal  SIGINT
7:38:39 PM web.1 Exited with exit code null
```

I'm a bit of a novice when it comes to front-end work, especially node. Anyone else run into this with this setup? Is there an easy way to just run `ghost local` or `heroku local` with this?

**Comment by kalverra** [comment]
Figured this out I believe. I added the line `dev: npm start --development` to the Procfile. Running with `heroku local dev` seems to have done the job. Not sure how this will affect the prod deploy, guess we'll find out.
