### ISSUE TITLE
Add support for Theme upload

### ISSUE THREAD

**Issue by aayushdutt** [SNathJr/ghost-on-heroku#9]
Due to the Ephimeral file system of Heroku, currently the admin panel doesn't support uploading the themes directly. If uploaded, the theme would go missing after some time. The only way to use custom theme currently is to commit your themes in the code files and then re publish the application.
It would be good if we could add support for theme upload directly via the admin panel.

**Comment by SNathJr** [comment]
Yes, you are absolutely right about the theme uploading issue. If you need to use this feature, I would recommend using AWS S3 as your file storage while building the application. I am still working on a viable way to enable theme uploads for free. If you have any service in mind, do share. Thank you.

**Comment by aayushdutt** [comment]
Integrating [Cloud Firestore](https://firebase.google.com/pricing) could be a good option.

**Comment by SNathJr** [comment]
Thank you. It looks promising. I will test it's integration with heroku in near future.

**Comment by aayushdutt** [comment]
Are you sure that in case of S3/Cloud Storage, the uploaded theme will not be stored in the file system? 
I guess S3 integration [docs](https://ghost.org/integrations/amazon-s3/) says it only serves the images
![image](https://user-images.githubusercontent.com/25280541/61173136-9daf9a80-a5ac-11e9-9147-9d94ce0ec759.png)

**Comment by SNathJr** [comment]
@aayushdutt My bad, I just verified that it does not support themes upload. I am looking into the [Ghost-Storage-Base](https://github.com/TryGhost/Ghost-Storage-Base) repository to make a storage adapter with themes storage enabled.

**Comment by codechair** [comment]
Voting for this enhancement 👍🏼

**Comment by SNathJr** [comment]
@codechair I still have not found a viable solution to this. Things either require paid subscriptions or do not support files other than static images. 
However, I will still be looking for other solutions (also considering to create a custom driver that syncs from remote on restart - such as a github private repo dump. But unless otherwise motivated, this will take time.)

**Comment by xjose97x** [comment]
> Things either require paid subscriptions or do not support files other than static images.

S3 supports any file types. Not only images.

**Comment by SNathJr** [comment]
Hey @xjose97x S3 does support all file types, however it requires you to have a paid AWS subscription, which many do not have.

**Comment by BadBrahmin** [comment]
Is this issue also the reason my gatsby + netlify deployment shows the default theme while my Heroku deployment shows the active theme?

**Comment by dwanderton** [comment]
+1

**Comment by jerinjacob1999** [comment]
You can clone a theme in local and edit as needed, push it to GitHub, and change the theme URL on the package.json file to your GitHub theme repo. Finally, deploy on Heroku.

**Comment by stephenajulu** [comment]
Great support @SNathJr 
Good job for this. 
I am using your button to build a ghost headless cms gatsby powered site.
Working on it now.

**Comment by vyronarediano** [comment]
"uploading the themes directly. If uploaded, the theme would go missing after some time. "

I also encountered this. Does anyone know how to solve this? Is there any workaround for this? 

Thanks in advance.

**Comment by jerinjacob1999** [comment]
> You can clone a theme in local and edit as needed, push it to GitHub, and change the theme URL on the package.json file to your GitHub theme repo. Finally, deploy on Heroku.
> 
> `"casper": "github:jerinjacob1999/Casper",`

@vyronarediano

**Comment by vyronarediano** [comment]
Hello @jerinjacob1999 , thanks for your response. 

how did you get the "github:jerinjacob1999/Casper"? is that a repository link?

I purchased a theme recently, you mean I should upload the theme to Github like a create a repo of that theme?

**Comment by jerinjacob1999** [comment]
@vyronarediano 
Create a respority with your favourite theme and add new or update existing theme in ```
package.json
``` in root directory, if your are adding new one you should aslo edit ```
copytheme.sh
``` in bin folder

**Comment by aayushdutt** [comment]
@vyronarediano
1. Fork this repository
2. Clone it and place your theme in `/content/themes`
3. Push the change
4. Deploy

I think this should work.

**Comment by vyronarediano** [comment]
> @vyronarediano
> Create a respority with your favourite theme and add new or update existing theme in `package.json` in root directory, if your are adding new one you should aslo edit `copytheme.sh` in bin folder

Ok. Thanks!

**Comment by vyronarediano** [comment]
> **To use a new theme:**
> 
> 1. Fork this repository
> 2. Clone it and copy your theme in `content/themes`
> 3. Push the change
> 4. Deploy
> 
> I think this should work @vyronarediano

Thanks for this @aayushdutt !! I will try this. Really appreciate your help :)

**Comment by vyronarediano** [comment]
Hello @aayushdutt, 

![image](https://user-images.githubusercontent.com/17285933/80813681-11369d00-8bfd-11ea-89ac-39fa01f16f50.png)

What should be the value of my theme?

**Comment by aayushdutt** [comment]
@vyronarediano You should copy the extracted contents inside `contents/themes`. No other change is needed.

**Comment by vyronarediano** [comment]
> @vyronarediano You should copy the extracted contents inside `contents/themes`. No other change is needed. If your new theme is named 'Editor', the folder should look like `content/themes/Editor/...`

Alright, I see @aayushdutt. 

How about what would be the value of the theme in package.json (see screenshot above)?

**Comment by aayushdutt** [comment]
As I said, no other change is needed. You don't need to change `package.json` at all.

**Comment by vyronarediano** [comment]
> As I said, no other change is needed. You don't need to change `package.json` at all. Just copy your theme and you are good to go.

One last thing, what would be the value of the theme in package.json?

**Comment by aayushdutt** [comment]
> > As I said, no other change is needed. You don't need to change `package.json` at all. Just copy your theme and you are good to go.
> 
> One last thing, what would be the value of the theme in package.json?

You don't need to change it. Just let it be what it is currently.
You will be able to see your new theme in the Ghost Admin panel

**Comment by vyronarediano** [comment]
> > > As I said, no other change is needed. You don't need to change `package.json` at all. Just copy your theme and you are good to go.
> > 
> > 
> > One last thing, what would be the value of the theme in package.json?
> 
> You don't need to change it. Just let it be what it is currently.
> You will be able to see your new theme in the Ghost Admin panel

Alright. Thank you so much for your help! Really appreciate it :)

**Comment by vyronarediano** [comment]
> u should copy the extracted contents inside `contents/themes`. No other change is needed. If your new theme is named 'Editor', the folder should look like `content/themes/Editor/...`

Hello @aayushdutt, I just copied the theme and made the folder look like the one you said but there were no changes to push. 

![image](https://user-images.githubusercontent.com/17285933/80862932-56b1a380-8cab-11ea-9052-2d036242e7db.png)

**Comment by jerinjacob1999** [comment]
@vyronarediano there will not be, becuase new folders, has to add manually, if you are using heroku free quota , I don't personally recommend this method,do thing as I told before.check my website.
cybergenie.tech

**Comment by aayushdutt** [comment]
@vyronarediano 
Oh, sorry my bad. I forgot to mention you need to remove `/content/themes/*` from .gitignore.
https://github.com/SNathJr/ghost-on-heroku/blob/842970dfe1741854bef1ce4eb5a6eb282c49ed79/.gitignore#L9

**Comment by aayushdutt** [comment]
> @vyronarediano there will not be, becuase new folders, has to add manually, if you are using heroku free quota , I don't personally recommend this method

@jerinjacob1999 could you please explain a bit more. I am sorry I couldn't get what you mean.

**Comment by vyronarediano** [comment]
> @vyronarediano
> Oh, sorry my bad. I forgot to mention you need to remove `content/themes/*` from `.gitignore`.
> https://github.com/SNathJr/ghost-on-heroku/blob/842970dfe1741854bef1ce4eb5a6eb282c49ed79/.gitignore#L9

Thank you @aayushdutt! Now I'm worried about the Theme might get stolen because it is a public repo.

**Comment by aayushdutt** [comment]
@vyronarediano  If you need to make your repo private, instead of forking this repository, do the following
1. Create a private repository 
2. Clone this repository
3. Update remote URL: `git remote set-url origin <remote-url>`
4. Proceed as normal in the next steps

Now your changes will be pushed to your private repository.

**Comment by vyronarediano** [comment]
> @vyronarediano If you need to make your repo private, instead of forking this repository, do the following
> 
> 1. Create a private repository
> 2. Clone this repository
> 3. Update remote URL: `git remote set-url origin <remote-url>`
> 4. Proceed as normal in the next steps
> 
> Now your changes will be pushed to your private repository.

Awesome. Thank you @aayushdutt for being helpful!

**Comment by kodrr** [comment]
> **To use a new theme:**
> 
> 1. Fork this repository
> 2. Clone it and copy your theme in `content/themes`
> 3. Remove `content/themes/*` from `.gitignore`
> 4. Push the change
> 5. Deploy
> 
> In case you wish to update existing deployment, follow [updating-source-code](https://github.com/vyronarediano/slp-on-heroku#updating-source-code) instead of step 4
> I think this should work @vyronarediano

@aayushdutt, Thanks for sharing if I do this by just upgrading the version of my theme and redeploy how about my previous changes, will it be save or will go back to the bare state of  site. Thanks!!!

**Comment by aayushdutt** [comment]
@kodrr All your data should be safe in the MySQL database. You don't need to worry about that.

**Comment by kodrr** [comment]
> @kodrr All your data should be safe in the MySQL database. You don't need to worry about that.

@aayushdutt, Actually I just did few minutes ago updating version of a theme by just editing package.json then pushing directly to heroku w/o cloning the theme itself to the content folder it seems this is more efficient for me. Thanks, Cheers!!!

**Comment by aayushdutt** [comment]
@kodrr yeah that is the best method for using and updating open source themes

**Comment by kasindhu** [comment]
> Hello @aayushdutt,
> 
> ![image](https://user-images.githubusercontent.com/17285933/80813681-11369d00-8bfd-11ea-89ac-39fa01f16f50.png)
> 
> What should be the value of my theme?
> 
> and as you said "Clone it and copy your theme in content/themes" - Is this in zip file format? or the extracted one? because upon uploading it in content/themes there were no changes to push.
> Only when I edit the package.json and copytheme.sh.
> 
> Many thanks in advance.

Sorry this is my doing. That theme is not public. I have removed accordingly from fork

**Comment by kasindhu** [comment]
Even after adding s3 storage backend, the only files uploaded are images. The theme is not uploaded to the S3 bucket.

**Comment by rista404** [comment]
I managed to upload my theme with these steps:


```sh
heroku git:clone -a your-app
cd your-app
git remote add origin https://github.com/SNathJr/ghost-on-heroku
git pull origin master
# extract zip file of your theme inside `content/themes` dir
# remove content/themes from .gitignore
git commit -am "Add theme"
git push heroku master # deploys the theme
```

**Comment by boxedpaul** [comment]
Thanks for all your help. I have had problems with the themes before and these instructions helped. Now I need to add some redirects via redirects.json. I'm expecting I'll have the same problems.

Do you have any suggestions for how to fix this? Happy to open another issue if it's not similar enough.

**Comment by talesmgodois** [comment]
Hello everybody. I just read what you guys did, But I still getting some problems.
My blog is posted in heroku, and I tried configuring the with the bucket data but I keep having the following error:

I don't have the following env S3_ASSET_HOST_URL. Not sure if this is the problem but I don't think this is it.


```
2020-08-14T21:46:57.740087+00:00 app[web.1]: AccessDenied: Access Denied
2020-08-14T21:46:57.740087+00:00 app[web.1]:     at Request.extractError (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/services/s3.js:585:35)
2020-08-14T21:46:57.740089+00:00 app[web.1]:     at Request.callListeners (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2020-08-14T21:46:57.740089+00:00 app[web.1]:     at Request.emit (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2020-08-14T21:46:57.740089+00:00 app[web.1]:     at Request.emit (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:683:14)
2020-08-14T21:46:57.740090+00:00 app[web.1]:     at Request.transition (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:22:10)
2020-08-14T21:46:57.740090+00:00 app[web.1]:     at AcceptorStateMachine.runTo (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
2020-08-14T21:46:57.740091+00:00 app[web.1]:     at /app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
2020-08-14T21:46:57.740091+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:38:9)
2020-08-14T21:46:57.740091+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:685:12)
2020-08-14T21:46:57.740092+00:00 app[web.1]:     at Request.callListeners (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2020-08-14T21:46:57.740092+00:00 app[web.1]:     at Request.emit (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2020-08-14T21:46:57.740093+00:00 app[web.1]:     at Request.emit (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:683:14)
2020-08-14T21:46:57.740094+00:00 app[web.1]:     at Request.transition (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:22:10)
2020-08-14T21:46:57.740094+00:00 app[web.1]:     at AcceptorStateMachine.runTo (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
2020-08-14T21:46:57.740094+00:00 app[web.1]:     at /app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
2020-08-14T21:46:57.740095+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:38:9)
2020-08-14T21:46:57.740095+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/request.js:685:12)
2020-08-14T21:46:57.740103+00:00 app[web.1]:     at Request.callListeners (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2020-08-14T21:46:57.740103+00:00 app[web.1]:     at callNextListener (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
2020-08-14T21:46:57.740103+00:00 app[web.1]:     at IncomingMessage.onEnd (/app/node_modules/ghost-storage-adapter-s3/node_modules/aws-sdk/lib/event_listeners.js:307:13)
2020-08-14T21:46:57.740104+00:00 app[web.1]:     at IncomingMessage.emit (events.js:203:15)
2020-08-14T21:46:57.740104+00:00 app[web.1]:     at IncomingMessage.EventEmitter.emit (domain.js:448:20)[39m
2020-08-14T21:46:57.740104+00:00 app[web.1]: [39m
```

**Comment by hegioncom** [comment]
> I managed to upload my theme with these steps:
> 
> ```shell
> heroku git:clone -a your-app
> cd your-app
> git remote add origin https://github.com/SNathJr/ghost-on-heroku
> git pull origin master
> # extract zip file of your theme inside `content/themes` dir
> # remove content/themes from .gitignore
> git commit -am "Add theme"
> git push heroku master # deploys the theme
> ```

### Great summary. I do have a question though:

Question 1: To remove content/themes from .gitignore, is it "**$ git add .**" ?
Question 2: I've tried to input **git commit -am "Add theme"**, but after pushing to master, I still don't see my custom theme (e.g. theme name -> Apple) stored 

Anyone there to help?


> ```shell
> heroku git:clone -a your-app
> cd your-app
> git remote add origin https://github.com/SNathJr/ghost-on-heroku
> git pull origin master
> # extract zip file of your theme inside `content/themes` dir
> # remove content/themes from .gitignore
> git commit -am "Add theme"
> git push heroku master # deploys the theme
> ```
